name: Java Docker CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-run:
    runs-on: [self-hosted, Windows, X64]  # Your self-hosted Windows runner with Docker

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 22
      - name: Set up Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      # Step 3: Build the Spring Boot app with Maven
      - name: Build Spring Boot app
        run: mvn -B clean package

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t java-docker-ci:${{ github.ref_name }} .

      # Step 5: Stop old container if exists
      - name: Stop previous container
        shell: pwsh
        run: |
          if (docker ps -a -q -f name=java-docker-ci) {
          docker stop java-docker-ci
          docker rm java-docker-ci
          } else {
          Write-Host "No existing container"
         }

      # Step 6: Run the container
      - name: Run container
        run: docker run -d --name java-docker-ci -p 8080:9021 java-docker-ci:${{ github.ref_name }}

      # Step 7: Test the endpoint
      - name: Test endpoint
        run: |
          timeout 10s powershell -Command "Start-Sleep -Seconds 10"
          curl -f http://localhost:9021 || exit 1
