name: Java Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 22
      - name: Set up Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      # Step 3: Build with Maven
      - name: Build Spring Boot app
        run: mvn -B clean package

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t java-docker-ci:latest .

      # (Optional) Step 5: Run container test
      - name: Run container
        run: docker run -d -p 8080:8080 java-docker-ci:latest

      # (Optional) Step 6: Check that it's up
      - name: Test endpoint
        run: |
          sleep 10
          curl -f http://localhost:8080 || exit 1
